// pet-app/components/ui/navbar/Navbar.vue
<script setup lang="ts">
import ThemeSwitcher from '~/components/ui/theme-switcher/ThemeSwitcher.vue';
</script>

<template>
    <nav
        class="sticky top-0 flex h-16 w-full items-center justify-between border-b-2 bg-transparent px-6 backdrop-blur md:px-16">
        <div class="flex items-center gap-4">
            <nuxt-img
                src="/img/icon.png"
                alt="Paws and Claws"
                class="h-8 w-8" />
            <h1 class="text-2xl font-semibold">Paws and Claws</h1>
        </div>
        <div>
            <ThemeSwitcher />
        </div>
    </nav>
</template>

<style scoped></style>

// pet-app/src/lib/components/ui/navbar/navbar.svelte
<script lang="ts">
		import ThemeSwitcher from "./theme-switcher.svelte";
		import logo from '$lib/assets/images/logo.png'
</script>

<nav class="sticky top-0 flex h-16 w-full items-center justify-between border-b-2 bg-transparent px-6 md:px-16 backdrop-blur">
	<div class="flex  gap-2 items-center justify-center">
		<img src={logo} alt="Paws and Claws" class="h-8 w-8" />
		<h1 class="font-semibold text-2xl">Paws and Claws</h1>
	</div>
	<div class="flex items-center justify-center gap-2">
		<ThemeSwitcher />
	</div>

</nav>
